### PR TITLE
Adding Tryggve use case page

### PR DESCRIPTION
**Pull request by JohannaKaunisvaara**
Created with Joel, Radovan and Antti a Tryggve Use Case page, including same info as here (https://wiki.neic.no/wiki/Tryggve_Getting_Started) + some updates.
Also added Wolanin's email address.
Link to this page needs to be added to Tryggve landing page (https://neic.no/tryggve/).

### CODE REVIEW

**Comment by bast** [comment]
Hi, this is maybe waiting for review (?) and also conflicting. It was probably me who made the README.md conflict with my recent changes. Do you need help resolving this?

**Comment by JohannaKaunisvaara** [comment]
Hi, 

Yes, could you check it? It mainly includes just the use case page, and when it's ok, the link should be added to Tryggve landing page (https://neic.no/tryggve/).

**Comment by bast** [comment]
OK I will send you (Johanna) a pull request that will resolve the conflict. And Joel can review everything else.

**Comment by bast** [comment]
... or somebody else. We should just be clear who should review this so that it can go in and does not wait for more conflicts.

**Comment by JohannaKaunisvaara** [comment]
Ok good! Could Joel do that?

**Comment by yohell** [comment]
Sure, @bast let me know when I'm on.

**Comment by bast** [comment]
@yohell it's good if you review changes before my fix goes in since it will bring in unrelated changes. Once you are happy with the changes, I will submit my fix, then Johanna needs to accept my fix, then I can accept the whole thing.

**Comment by bast** [comment]
Or simpler/cleaner: after your review I will integrate the changes "manually", resolving conflicts at the same time.

**Comment by yohell** [comment]
uhhhhhhhh nope lost me. What do you want me to review when?

**Comment by bast** [comment]
I will ask differently: is this PR ready to go in (apart from the conflict in README.md)?

**Comment by yohell** [comment]
Right, sure, it's fantastic, outstanding, marvellous! Get this good stuff out right now asap.

**Comment by bast** [comment]
OK the code is now in. Closing.

**Comment by JohannaKaunisvaara** [comment]
Great, thanks!

**Pull request merged**
