### PR TITLE
update CodeRefinery SG list

### PR DESCRIPTION
**Pull request by bast**

### CODE REVIEW

**Comment by bast** [comment]
Please don't merge yet. I was now informed that this is wrong. Correction incoming.

**Comment by bast** [comment]
Corrected - ready to go.

**Comment by caela** [comment]
she's not really on contract, or is she??

**Comment by bast** [comment]
OK I will fix that.

**Comment by bast** [comment]
Fixed.

**Review by caela — APPROVED** [review]
looks good now

**Pull request merged**
