### PR TITLE
Tryggve2 and Tryggve page updates

### PR DESCRIPTION
**Pull request by JohannaKaunisvaara**
Some minor changes in these pages. @yohell to check these.

### CODE REVIEW

**Comment by bast** [comment]
On top right you should be able to suggest reviewers (?). But the way you did it - with a mention - also notifies people. Also these changes conflict. Is this under control?

**Comment by yohell** [comment]
nah :)

I'm attempting to pull in the differences locally now, to update the fork from my end. Either this'll work or explode lol

cf slack

**Comment by yohell** [comment]
From discussion on slack: Looking at the changes, you have set "type" to "Nordic Collaboration for Sensitive Data", whereas the intended use of "type" is to reflect what type of activity this is, concretely if it is a "project" or "operations". This communicates what info people can expect to find on there; for example like good projects end whereas good operations don't. Cf all other neic activities, https://johannakaunisvaara.github.io/neic.no/nt1/ https://johannakaunisvaara.github.io/neic.no/deepdive/ etc...

Though we do want someting that says "Nordic Collaboration for Sensitive Data" up top. I'll see if I can add a "tagline" slot to the template that does this.

**Comment by yohell** [comment]
I made some changes as we discussed on slack.

Most relevant pages to look at:

https://johannakaunisvaara.github.io/neic.no/ (no tryggve2 listed)
https://johannakaunisvaara.github.io/neic.no/tryggve/ (has tagline below h1 name)
https://johannakaunisvaara.github.io/neic.no/tryggve2/ (links to /tryggve/)

Please review and see that this is acceptable nomenclature (@antti-pur), looks (@JohannaKaunisvaara?), and html/css styling (@bast?).

**Comment by bast** [comment]
Looks good from my perspective! Thanks - this is a nice example PR which makes it easy to check the changes.

**Comment by JohannaKaunisvaara** [comment]
Perfect, thanks Joel!

**Comment by antti-pur** [comment]
Hi all,

looks very good; except NeIC management don’t want niece.no/tryggve page to have “PROGRAM” in it. 

That field should be left blank. Otherwise please publish

Thanks,
 Antti



---
Antti Pursula, Program Director, Research Infrastructures
CSC - IT Center for Science Ltd, http://www.csc.fi <http://www.csc.fi/>
email: antti.pursula@csc.fi <mailto:antti.pursula@csc.fi>, tel: +358-50-3819537
twitter: @AnttiPursula

**Comment by yohell** [comment]
Thought as much, didn't I :D

Merged!

/Joel

**Pull request merged**
